# Prompt for few-shot inference with OpenAI API for GSM8K

few_shot_examples:
  prefix: ""
  template: |-
    Given the following problem, reason and give a final answer to the problem.
    Problem: {problem}
    Your response should end with "The final answer is \boxed{{[answer]}}" where [answer] is the response to the problem.

    {solution}

  suffix: ""
  examples_type: gsm8k_text_detailed

system: ""

user: |-
  {examples}Given the following problem, reason and give a final answer to the problem.
  Problem: {problem}
  Your response should end with "The final answer is \boxed{{[answer]}}" where [answer] is the response to the problem. 