FROM vllm/vllm-openai:v0.8.3

ARG OPENRLHF_COMMIT=9001bc7026517e8f51682978c52cc41eb1d2c563
RUN cd /opt && git clone https://github.com/Kipok/OpenRLHF && \
    cd OpenRLHF && git checkout $OPENRLHF_COMMIT && \
    pip install -e .