FROM lmsysorg/sglang:v0.4.6.post1-cu125

# to fix https://github.com/sgl-project/sglang/issues/5002
ARG LIB_PATH=/usr/local/lib/python3.10/dist-packages/nvidia/
ENV LD_LIBRARY_PATH=${LIB_PATH}/cuda_nvrtc/lib/:${LIB_PATH}/cublas/lib:${LIB_PATH}/cuda_runtime/lib/:${LD_LIBRARY_PATH}

# patching for sharding states support for DeepSeek-R1
COPY dockerfiles/sglang.patch /sgl-workspace/sglang.patch
RUN cd /sgl-workspace/sglang && git apply /sgl-workspace/sglang.patch