FROM verlai/verl:ngc-th2.4.0-cu124-vllm0.6.3-te1.7-v0.0.4

# Set working directory
WORKDIR /opt

# Install verl
ENV VERL_COMMIT=62aaebb5accb65569b4d5b0e9fb03b55ed1c60a0
RUN git clone https://github.com/titu1994/verl.git && \
    cd verl && \
    git checkout $VERL_COMMIT && \
    pip3 install -e .

# Install vllm flash-attn
RUN pip3 uninstall -y vllm flash-attn
RUN pip3 install vllm>=0.7.3
RUN MAX_JOBS=4 NINJA_FLAGS="-j4" pip3 install --no-cache-dir --no-build-isolation flash-attn
RUN pip3 install -U pynvml

WORKDIR /workspace

# Fix CV2
RUN pip install opencv-fixer==0.2.5 && \
    python -c "from opencv_fixer import AutoFix; AutoFix()"

# Run additional dependencies
RUN pip install math-verify[antlr4_9_3] ray[default] pylatexenc wandb

CMD ["/usr/bin/bash"]