FROM lmsysorg/sglang:v0.4.6.post5-cu124

# patching for sharding states support for DeepSeek-R1
COPY dockerfiles/sglang.patch /sgl-workspace/sglang.patch
RUN cd /sgl-workspace/sglang && git apply /sgl-workspace/sglang.patch