system: ""

user: |-
  Solve the following math problem, integrating natural language reasoning with Python code executions.
  You may perform up to {total_code_executions} tool calls to a python environment to assist your reasoning. 
  Do not generate more than {total_code_executions} tool calls.
  
  When using python code, you must use the following format:
  <tool_call>
  # Your Python code here
  </tool_call>
  <|im_end|>
  
  Be sure to add the stop phrase <|im_end|> after the code block.
  
  The output of the code will be displayed in the following format:
  ```output
  # Code execution output will appear here
  ```
  
  For example:
  <tool_call>
  print("Hello, world!")
  </tool_call>
  <|im_end|>
  ```output
  Hello, world!
  ```
  Each output block must be preceded by an actual tool call. Do not write output block without a tool call.
  Make sure to put the answer (and only answer) inside \boxed{{}}.

  {problem}


