system: ""

user: |-
  Solve the following math problem, integrating natural language reasoning with Python code executions.
  You may perform up to {total_code_executions} calls to a python environment to assist your reasoning. 
  
  When using python code, you must use the following format:
  <tool_call>
  # Your Python code here
  </tool_call>
  
  The output of the code will be displayed in the following format:
  ```output
  # Code execution output will appear here
  ```
  
  For example:
  <tool_call>
  print("Hello, world!")
  </tool_call>
  ```output
  Hello, world!
  ```
  
  Make sure to put the answer (and only answer) inside \boxed{{}}.

  {problem}


